API_KEY:
  GROQ_API_KEY_1:  "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"
  GROQ_API_KEY_2:  "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"
  GROQ_API_KEY_3:  "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"
  GROQ_API_KEY_4:  "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"
  GROQ_API_KEY_5:  "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"
  GROQ_API_KEY_6:  "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"
  GROQ_API_KEY_7:  "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"
  GROQ_API_KEY_8:  "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"
  GROQ_API_KEY_9:  "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"
  GROQ_API_KEY_10: "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"

MODEL: "llama3-8b-8192"